### ISSUE TITLE
Order of tournament data entered effects the final ratings of participants

### ISSUE THREAD

**Issue by BenKatin** [bliutwo/django-glicko2#1]
currently, when the order of the lines of tournaments entered is reversed entrants will have different ratings. A fix would be to first categorize all the tournaments by the time they happened on, and then use the rating system on them in sequential order of time.

**Comment by bliutwo** [comment]
Fixed by https://github.com/bliutwo/django-glicko2/commit/2b662ab3e4b7fd92561e4f8818f243b67b6e0ced which uses a priority queue and the datetime-stamp of when the match started to order the matches.

**Comment by bliutwo** [comment]
Fixed by https://github.com/bliutwo/django-glicko2/commit/2b662ab3e4b7fd92561e4f8818f243b67b6e0ced which uses a priority queue and the datetime-stamp of when the match started to order the matches.
